server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finaciamiento
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

#jpa:
#  hibernate:
#    ddl-auto: update
